---
metadata:
  name: Dabble Lab
  short_name: dabble lab
  description: Tutorials and templates for creating Alexa skills, Google Actions, and Twilio Autopilot bots.
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: TUTORIALS
      link: https://dabblelab.com/tutorials
      external: true
    - text: TEMPLATES
      link: https://www.gatsbyjs.org
      external: true
    - text: COURSES
      link: https://dabblelab.com/courses
      external: true

sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/demo"
      title: ":rocket: Demo"

    - order: 2
      path: "/gettingstarted"
      title: ":rocket: Getting Started"

    - order: 3
      path: "/configuration"
      title: ":wrench: Configuration"

    - order: 4
      path: "/editing"
      title: ":writing_hand: Editing Content"

    - order: 5
      path: "/deployment"
      title: ":rocket: Deployment"

    - order: 6
      path: "/developing"
      title: ":computer: Developing"

  links:
    - text: Visit YouTube channel
      link: https://www.youtube.com/channel/UCfY-LopSxGekh9LruXLjffg
    - text: Visit GitHub 
      link: https://github.com/dabblelab
  ignoreIndex: false
  # poweredBy:
  #   trademark: "/assets/gatsby.png"
  #   name: GatsbyJS
  #   link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  github: https://github.com/dabblelab
  linkedin: https://www.linkedin.com/company/dabblelab
  twitter: https://twitter.com/dabblelab

features:
  darkMode:
    enabled: true  
    default: false
  editOnRepo:
    location: https://github.com/dabblelab/dabblelab-documentation-site 
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
